manual_heading = "\\textit{Submitted, in review, or in revision:}"

[[published_overrides]]
match_title = "Climate change-resilient snowpack estimation in the Western United States"
sort_date = "2024-07-01"
text = '''\textbf{Cowherd, M.}, Mital, U., Rahimi, S., Girotto, M., Schwartz, A., and Feldman, D. Climate change-resilient snowpack estimation in the Western United States. (2024) \textit{Communications Earth \& Environment}. \textcolor{blue} {Media: \href{https://www.kcra.com/article/climate-change-estimate-sierra-snowpack-ai/61603975}{KCRA3 News Sacramento}, \href{https://www.energy.gov/science/articles/when-summer-drought-begins-winter-investigating-snow-drought}{DOE Office of Science}}'''

[[published_overrides]]
match_title = "Identifying snowfall elevation patterns by assimilating satellite-based snow depth retrievals"
sort_date = "2024-01-01"
text = '''Girotto, M., Formetta, G., Azimi, S., Bachand, C., \textbf{Cowherd, M.}, De Lannoy, G., Lievens, H., Modanesi, S., Raleigh, M.S., Rigon, R., and Massari, C. (2024) Identifying snowfall elevation gradients by assimilating satellite-based snow depth observations. \textit{Science of the Total Environment.}'''

[[published_overrides]]
match_title = "Evolution of global snow drought characteristics from 1850 to 2100"
sort_date = "2023-01-01"
text = '''\textbf{Cowherd, M.}, Leung, L.R., and Girotto, M. (2023) Evolution of global snow drought characteristics from 1850 to 2100. \textit{Environmental Research Letters.}'''

[[published_overrides]]
match_title = "Phase‐resolved wave boundary layer dynamics in a shallow estuary"
sort_date = "2021-01-01"
text = '''\textbf{Cowherd, M.}, Egan, G., Fringer, O., Monismith, S. (2021). Wave phase-decomposed velocity profile observations in a shallow estuary. \textit{Geophysical Research Letters.}'''

[[published_overrides]]
match_title = "Observations of near‐bed shear stress in a shallow, wave‐and current‐driven flow"
sort_date = "2019-01-01"
text = '''Egan, G., \textbf{Cowherd, M.}, Fringer, O., Monismith, S. (2019). Observations of near‐bed shear stress in a shallow, wave‐ and current‐driven flow. \textit{Journal of Geophysical Research: Oceans.}'''

[[manual_entries]]
sort_date = "2025-02-01"
text = '''\textbf{Cowherd, M.}, Schwartz, A., Marks, J. Brandt, G., Kim, L., Collins, B., Stephens, S., and Girotto, M. Low severity fire retains snow longer in a California megafire. \textit{submitted}'''

[[manual_entries]]
sort_date = "2025-01-01"
text = '''\textbf{Cowherd, M.}, Rahimi, S., Vargas Zeppetello, L., Hall, A., and Girotto, M. Surface and atmosphere drivers of snow drought are topography-dependent. \textit{in revision}'''
