[[entries]]
sort_date = "2026-03-01"
review_state = "submitted"
status_label = "submitted to \\emph{PNAS}"
include_in_selected_research = true
text = '''\textbf{Malsky, I.}, Zhang, X., Kataria, T., Graham, M., Huang, Z., Bonev, B., Tsai, S.-M., Lee, E. K. H., \textsc{Accelerating Chemical Kinetics for Exoplanet Atmospheres using Neural Networks}'''

[[entries]]
sort_date = "2026-02-01"
review_state = "submitted"
status_label = "submitted to \\emph{ApJ}"
include_in_selected_research = true
text = '''\textbf{Malsky, I.} and Kataria, T., \textsc{Accelerating Radiative Transfer for Planetary Atmospheres by Orders of Magnitude with a Transformer-Based Machine Learning Model}'''
